name: growx
version: '0.2'
base: core18
summary: Grow your plant and your Business
description: python edge ( psutils, bluepy )
confinement: devmode
grade: stable

    
apps:

  desktop-launch:
    command: bin/desktop-launch
    plugs:
      - desktop

  growx-daemon: 
    command: sh $SNAP/bin/run.sh
    plugs: [network, network-bind, mount-observe, network-observe, system-observe, bluetooth-control]
    daemon: simple
    restart-condition: on-failure
    
  flask-daemon: 
    command: sh $SNAP/bin/flask.sh  
    plugs: [network, network-bind, mount-observe, network-observe, system-observe, bluetooth-control]
    daemon: simple
    restart-condition: on-failure
    
  run: 
    command: sh $SNAP/bin/run.sh 
    plugs: [network, network-bind, mount-observe, network-observe, system-observe, bluetooth-control]

  info: 
    command: sh $SNAP/bin/info.sh  
    plugs: [network, network-bind, mount-observe, network-observe, system-observe, bluetooth-control]

parts:


  pymongo-part:
    plugin: python
    python-version: python3
    python-packages: [pymongo]
    build-packages:
      - python3-dev 
      - build-essential
   

  influxdb-part:
    plugin: python
    python-version: python3
    python-packages: [influxdb]
    build-packages:
      - python3-dev
      - build-essential
   

  paho-mqtt-part:
    plugin: python
    python-version: python3
    python-packages: [paho-mqtt]
    build-packages:
      - python3-dev
      - build-essential
      
  flask-part:
    plugin: python
    python-version: python3
    python-packages: [flask]
    build-packages:
      - python3-dev
      - build-essential

  bluepy:
    plugin: python
    python-version: python3
    source: https://github.com/IanHarvey/bluepy
    source-type: git
    build-packages: [libglib2.0-dev]

  miflora:
    plugin: python
    python-version: python3
    python-packages: [miflora]
    build-packages:
      - python3-dev
      - build-essential

  python-libs:  
    source: ./lib/
    plugin: dump
    organize:
      '*': /lib/python3.6/site-packages/

  python-code:  
    source: ./pythoncode/
    plugin: dump
    organize:
      '*': bin/pythoncode/

  shscripts:  
    source: ./shscripts/
    plugin: dump
    organize:
      '*': bin/

  
  


  
