name: growx
version: '0.3'
summary: you can grow your business with us
description: python edge ( psutils, bluepy )
confinement: devmode
grade: stable

    
apps:
  python-bluepy: 
    command: sh $SNAP/bin/run.sh  
    plugs: [network, network-bind, mount-observe, network-observe, system-observe, bluetooth-control]
    daemon: simple

  run: 
    command: sh $SNAP/bin/run.sh  
    plugs: [network, network-bind, mount-observe, network-observe, system-observe, bluetooth-control]

  info: 
    command: sh $SNAP/bin/info.sh  
    plugs: [network, network-bind, mount-observe, network-observe, system-observe, bluetooth-control]

parts:


  pymongo-part:
    plugin: python
    python-version: python3
    python-packages: [pymongo]
    build-packages:
      - python3-dev 
      - build-essential
   

  influxdb-part:
    plugin: python
    python-version: python3
    python-packages: [influxdb]
    build-packages:
      - python3-dev
      - build-essential
   

  paho-mqtt-part:
    plugin: python
    python-packages: [paho-mqtt]
    build-packages:
      - python3-dev
      - build-essential

  bluepy:
    plugin: python
    python-version: python3
    source: https://github.com/IanHarvey/bluepy
    source-type: git
    build-packages: [libglib2.0-dev]

  miflora:
    plugin: python
    python-version: python3
    python-packages: [miflora]
    build-packages:
      - python3-dev
      - build-essential

  apython-libs:  
    source: ./lib/
    plugin: dump
    organize:
      '*': /lib/python3.5/site-packages/

  apython-code:  
    source: ./pythoncode/
    plugin: dump
    organize:
      '*': bin/pythoncode/

  a-shscripts:  
    source: ./shscripts/
    plugin: dump
    organize:
      '*': bin/

  
  


  
