name: growx
version: '1.0'
base: core18
summary: GrowX the Opensource Greenhouse monitoring App
description: |
      ** GrowX **

      GrowX allows to monitor your greenhouse using standard consumer sensors. Currently we are
      supporting the Xiaomi MiFlora and the Xiaomi Mijia Hygrothermo v2 (LYWSDCGQ) but we are        
      planning to expand the number of supported devices.
      
confinement: strict
grade: stable

    
apps:

  desktop-launch:
    command: bin/desktop-launch
    plugs:
      - desktop

  webserver: 
    command: bin/runserver.sh 
    plugs: [network, network-bind, mount-observe, network-observe, system-observe, bluetooth-control]
    daemon: simple
    restart-condition: always
    
  growx-daemon: 
    command: bin/run.sh
    plugs: [network, network-bind, mount-observe, network-observe, system-observe, bluetooth-control]
    daemon: simple
    restart-condition: always
    
  
  influxd:
        command: bin/runinfluxd.sh
        plugs: [network, network-bind]
        daemon: simple
        restart-condition: always
        environment:
          INFLUXDB_META_DIR: $SNAP_COMMON/meta
          INFLUXDB_DATA_DIR: $SNAP_COMMON/data
          INFLUXDB_DATA_WAL_DIR: $SNAP_COMMON/wal
          INFLUXDB_CONFIG_PATH: $SNAP_COMMON/conf/influxdb.conf
          INFLUXD_BOLT_PATH: $SNAP_COMMON/influxdbv2/influxd.bolt
          INFLUXD_ENGINE_PATH: $SNAP_COMMON/influxdbv2/engine

  influx:
        command: usr/bin/influx
        plugs: [network, network-bind]
        
  default-client:
        command: bin/defaultclient.sh
        plugs: [network, network-bind]
    
  run: 
    command: bin/run.sh 
    plugs: [network, network-bind, mount-observe, network-observe, system-observe, bluetooth-control]

  info: 
    command: bin/info.sh  
    plugs: [network, network-bind, mount-observe, network-observe, system-observe, bluetooth-control]

parts:


  pymongo-part:
    plugin: python
    python-version: python3
    python-packages: [pymongo]
    build-packages:
      - python3-dev 
      - build-essential
   

  influxdb-part:
    plugin: python
    python-version: python3
    python-packages: [influxdb]
    build-packages:
      - python3-dev
      - build-essential
   

  paho-mqtt-part:
    plugin: python
    python-version: python3
    python-packages: [paho-mqtt]
    build-packages:
      - python3-dev
      - build-essential
      
  flask-part:
    plugin: python
    python-version: python3
    python-packages: [flask]
    build-packages:
      - python3-dev
      - build-essential

  bluepy:
    plugin: python
    python-version: python3
    source: https://github.com/IanHarvey/bluepy
    source-type: git
    build-packages: [libglib2.0-dev]

  miflora:
    plugin: python
    python-version: python3
    python-packages: [miflora]
    build-packages:
      - python3-dev
      - build-essential
      
  influxdb:
        plugin: dump
        source:
         - on amd64: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.3_amd64.deb
         - on arm64: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.3_arm64.deb
         - on armhf: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.3_armhf.deb
         - on i386: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.3_i386.deb
        stage-packages:
            - libssl1.1
            - libcurl3-dev
            - libcurl4-openssl-dev

  nodejs:
    plugin: nodejs
    source: .
  
  
  node-code:  
    source: ./node-code/
    plugin: dump
    organize:
      '*': bin/

  


  python-libs:  
    source: ./lib/
    plugin: dump
    organize:
      '*': /lib/python3.6/site-packages/

  python-code:  
    source: ./pythoncode/
    plugin: dump
    organize:
      '*': bin/pythoncode/

  shscripts:  
    source: ./shscripts/
    plugin: dump
    organize:
      '*': bin/

  
  


  
