#!/bin/sh -e

# ensure the conf directory exists
if [ ! -d "$SNAP_DATA/conf" ]; then
	mkdir -p "$SNAP_DATA/conf"
fi

# copy the default config file 
cp "$SNAP/bin/conf/influxdb.conf" "$SNAP_DATA/conf/influxdb.conf"
