#!/bin/sh -e

# ensure the conf directory exists
if [ ! -d "$SNAP_COMMON/conf" ]; then
	mkdir -p "$SNAP_COMMON/conf"
	# copy the default config file 
        cp "$SNAP/bin/conf/influxdb.conf" "$SNAP_COMMON/conf/influxdb.conf"
fi

touch $SNAP_DATA/unlicensed
